# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopList_name', models.CharField(max_length=100)),
                ('list_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listService.ListElement')),
            ],
        ),
    ]
